M48
; DRILL file {KiCad (6.0.9)} date Sat Jan 14 14:27:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-14T14:27:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.540
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X66.615Y-83.45
X66.615Y-96.15
T2
X55.0Y-55.0
X55.0Y-145.0
X145.0Y-55.0
X145.0Y-145.0
T0
M30
