M48
; DRILL file {KiCad (6.0.9)} date Fri Apr  7 16:32:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-07T16:32:21+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.6226Y-3.2854
X2.6226Y-3.7854
T2
X2.1654Y-2.1654
X2.1654Y-5.7087
X5.7087Y-2.1654
X5.7087Y-5.7087
T0
M30
